apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: abdullah-pvc
  namespace: abdullah
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: abdullah-sc
