apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: abdullah-sc
  namespace: abdullah
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
parameters:
  type: gp2
allowedTopologies:
- matchLabelExpressions:
  - key: topology.kubernetes.io/zone
    values:
      - ap-south-1a   # replace with your node's AZ

