# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: {{ .Values.mongoStorageClass.name }}
# provisioner: {{ .Values.mongoStorageClass.provisioner }}
# reclaimPolicy: {{ .Values.mongoStorageClass.reclaimPolicy }}
# volumeBindingMode: {{ .Values.mongoStorageClass.volumeBindingMode }}
# parameters:
#   type: {{ .Values.mongoStorageClass.type }}

